local M = {}

function M.get(c)
  return {
    -- blink.cmp and blink-cmp-words
    BlinkCmpMenu = { link = "Pmenu" },
    BlinkCmpMenuBorder = { link = "FloatBorder" },
    BlinkCmpMenuSelection = { link = "PmenuSel" },
    BlinkCmpLabel = { fg = c.fg, bg = c.bg_popup },
    BlinkCmpLabelDeprecated = { fg = c.fg_muted, bg = c.bg_popup, strikethrough = true },
    BlinkCmpLabelMatch = { fg = c.wheat, bg = c.bg_popup, bold = true },
    BlinkCmpLabelDetail = { link = "PmenuExtra" },
    BlinkCmpLabelDescription = { link = "PmenuExtra" },
    BlinkCmpKind = { link = "PmenuKind" },
    BlinkCmpSource = { link = "PmenuExtra" },
    BlinkCmpGhostText = { fg = c.fg_hidden },
    BlinkCmpDoc = { link = "NormalFloat" },
    BlinkCmpDocBorder = { link = "FloatBorder" },
    BlinkCmpDocSeparator = { fg = c.separator, bg = c.bg_popup },
    BlinkCmpDocCursorLine = { link = "CursorLine" },
    BlinkCmpSignatureHelp = { link = "NormalFloat" },
    BlinkCmpSignatureHelpBorder = { link = "FloatBorder" },
    BlinkCmpSignatureHelpActiveParameter = { fg = c.wheat, bold = true },
    BlinkCmpScrollBarGutter = { link = "PmenuSbar" },
    BlinkCmpScrollBarThumb = { link = "PmenuThumb" },
    BlinkCmpKindFunction = { fg = c.function_color, bg = c.bg_popup },
    BlinkCmpKindMethod = { link = "BlinkCmpKindFunction" },
    BlinkCmpKindConstructor = { fg = c.keyword_color, bg = c.bg_popup },
    BlinkCmpKindClass = { fg = c.type_color, bg = c.bg_popup },
    BlinkCmpKindInterface = { link = "BlinkCmpKindClass" },
    BlinkCmpKindStruct = { link = "BlinkCmpKindClass" },
    BlinkCmpKindTypeParameter = { fg = c.fg_dim, bg = c.bg_popup },
    BlinkCmpKindField = { fg = c.variable_color, bg = c.bg_popup },
    BlinkCmpKindProperty = { link = "BlinkCmpKindField" },
    BlinkCmpKindVariable = { link = "BlinkCmpKindField" },
    BlinkCmpKindKeyword = { fg = c.keyword_color, bg = c.bg_popup },
    BlinkCmpKindConstant = { fg = c.constant_color, bg = c.bg_popup },
    BlinkCmpKindValue = { fg = c.number_color, bg = c.bg_popup },
    BlinkCmpKindNumber = { link = "BlinkCmpKindValue" },
    BlinkCmpKindBoolean = { fg = c.olive, bg = c.bg_popup },
    BlinkCmpKindEnum = { link = "BlinkCmpKindBoolean" },
    BlinkCmpKindEnumMember = { fg = c.olive, bg = c.bg_popup },
    BlinkCmpKindText = { fg = c.string_color, bg = c.bg_popup },
    BlinkCmpKindSnippet = { link = "BlinkCmpKindText" },
    BlinkCmpKindModule = { fg = c.fg_dim, bg = c.bg_popup },
    BlinkCmpKindFolder = { fg = c.ochre, bg = c.bg_popup },
    BlinkCmpKindFile = { fg = c.fg, bg = c.bg_popup },
    BlinkCmpKindReference = { fg = c.slate, bg = c.bg_popup },
    BlinkCmpKindOperator = { fg = c.fg_dim, bg = c.bg_popup },

    -- nvim-cmp
    CmpItemAbbr = { link = "Pmenu" },
    CmpItemAbbrMatch = { link = "PmenuMatch" },
    CmpItemAbbrMatchFuzzy = { link = "PmenuMatch" },
    CmpItemAbbrDeprecated = { fg = c.fg_muted, strikethrough = true },
    CmpItemKind = { link = "PmenuKind" },
    CmpItemMenu = { link = "PmenuExtra" },
    CmpItemKindFunction = { fg = c.function_color },
    CmpItemKindMethod = { link = "CmpItemKindFunction" },
    CmpItemKindConstructor = { fg = c.keyword_color },
    CmpItemKindClass = { fg = c.type_color },
    CmpItemKindInterface = { link = "CmpItemKindClass" },
    CmpItemKindStruct = { link = "CmpItemKindClass" },
    CmpItemKindTypeParameter = { fg = c.fg_dim },
    CmpItemKindField = { fg = c.variable_color },
    CmpItemKindProperty = { link = "CmpItemKindField" },
    CmpItemKindVariable = { link = "CmpItemKindField" },
    CmpItemKindKeyword = { fg = c.keyword_color },
    CmpItemKindConstant = { fg = c.constant_color },
    CmpItemKindValue = { fg = c.number_color },
    CmpItemKindNumber = { link = "CmpItemKindValue" },
    CmpItemKindBoolean = { fg = c.olive },
    CmpItemKindEnum = { link = "CmpItemKindBoolean" },
    CmpItemKindEnumMember = { link = "CmpItemKindBoolean" },
    CmpItemKindText = { fg = c.string_color },
    CmpItemKindSnippet = { link = "CmpItemKindText" },
    CmpItemKindModule = { fg = c.fg_dim },
    CmpItemKindFolder = { fg = c.ochre },
    CmpItemKindFile = { fg = c.fg },
    CmpItemKindReference = { fg = c.slate },
    CmpItemKindOperator = { fg = c.fg_dim },
  }
end

return M
