-- Generated by scripts/extras.lua
return {
  foreground = "#ada9a3",
  background = "#101010",
  cursor_bg = "#c0bbb3",
  cursor_fg = "#101010",
  selection_bg = "#292724",
  selection_fg = "#c0bbb3",
  ansi = { "#080808", "#9a7477", "#7f8c77", "#a38762", "#788184", "#8d818a", "#837f78", "#ada9a3" },
  brights = { "#393632", "#9b7469", "#768569", "#97916f", "#837f78", "#9a7869", "#788184", "#c0bbb3" },
}
