local M = {}

function M.get(c)
  return {
    -- neo-tree.nvim
    NeoTreeNormal = { link = "Normal" },
    NeoTreeNormalNC = { link = "Normal" },
    NeoTreeFloatNormal = { link = "NormalFloat" },
    NeoTreeFloatBorder = { link = "FloatBorder" },
    NeoTreeFloatTitle = { link = "FloatTitle" },
    NeoTreeSignColumn = { link = "SignColumn" },
    NeoTreeStatusLine = { link = "StatusLine" },
    NeoTreeStatusLineNC = { link = "StatusLineNC" },
    NeoTreeVertSplit = { link = "WinSeparator" },
    NeoTreeWinSeparator = { link = "WinSeparator" },
    NeoTreeEndOfBuffer = { link = "EndOfBuffer" },
    NeoTreeCursorLine = { link = "CursorLine" },
    NeoTreeDirectoryName = { link = "Directory" },
    NeoTreeDirectoryIcon = { link = "Directory" },
    NeoTreeFileName = { fg = c.fg },
    NeoTreeFileNameOpened = { fg = c.fg_bright, bold = true },
    NeoTreeFileIcon = { fg = c.fg },
    NeoTreeRootName = { fg = c.fg_bright, bold = true },
    NeoTreeSymbolicLinkTarget = { fg = c.information },
    NeoTreeIndentMarker = { fg = c.indent },
    NeoTreeExpander = { fg = c.fg_hidden },
    NeoTreeDotfile = { fg = c.fg_muted },
    NeoTreeHiddenByName = { link = "NeoTreeDotfile" },
    NeoTreeIgnored = { link = "NeoTreeDotfile" },
    NeoTreeGitIgnored = { link = "NeoTreeDotfile" },
    NeoTreeDimText = { fg = c.fg_muted },
    NeoTreeFileStats = { fg = c.fg_muted },
    NeoTreeFileStatsHeader = { fg = c.fg_dim },
    NeoTreeFilterTerm = { fg = c.type },
    NeoTreeModified = { fg = c.warning },
    NeoTreeGitAdded = { link = "LimeiAdded" },
    NeoTreeGitDeleted = { link = "LimeiRemoved" },
    NeoTreeGitModified = { link = "LimeiChanged" },
    NeoTreeGitConflict = { fg = c.conflict, bold = true },
    NeoTreeGitRenamed = { fg = c.transform },
    NeoTreeGitStaged = { fg = c.success },
    NeoTreeGitUnstaged = { fg = c.warning },
    NeoTreeGitUntracked = { fg = c.literal },
    NeoTreeTabActive = { link = "TabLineSel" },
    NeoTreeTabInactive = { link = "TabLine" },
    NeoTreeTabSeparatorActive = { link = "WinSeparator" },
    NeoTreeTabSeparatorInactive = { link = "WinSeparator" },
    NeoTreePreview = { link = "Search" },

    -- nvim-tree.lua
    NvimTreeNormal = { link = "Normal" },
    NvimTreeNormalNC = { link = "Normal" },
    NvimTreeNormalFloat = { link = "NormalFloat" },
    NvimTreeNormalFloatBorder = { link = "FloatBorder" },
    NvimTreeWinSeparator = { link = "WinSeparator" },
    NvimTreeEndOfBuffer = { link = "EndOfBuffer" },
    NvimTreeSignColumn = { link = "SignColumn" },
    NvimTreeCursorLine = { link = "CursorLine" },
    NvimTreeCursorLineNr = { link = "CursorLineNr" },
    NvimTreeStatusLine = { link = "StatusLine" },
    NvimTreeStatusLineNC = { link = "StatusLineNC" },
    NvimTreeRootFolder = { fg = c.fg_bright, bold = true },
    NvimTreeFolderName = { link = "Directory" },
    NvimTreeEmptyFolderName = { link = "Directory" },
    NvimTreeOpenedFolderName = { link = "Directory" },
    NvimTreeSymlinkFolderName = { link = "Directory" },
    NvimTreeFolderIcon = { link = "Directory" },
    NvimTreeOpenedFolderIcon = { link = "Directory" },
    NvimTreeClosedFolderIcon = { link = "Directory" },
    NvimTreeFolderArrowClosed = { fg = c.fg_hidden },
    NvimTreeFolderArrowOpen = { fg = c.fg_hidden },
    NvimTreeIndentMarker = { fg = c.indent },
    NvimTreeFileIcon = { fg = c.fg },
    NvimTreeSymlink = { fg = c.information, underline = true },
    NvimTreeSymlinkIcon = { fg = c.information },
    NvimTreeWindowPicker = { fg = c.fg_bright, bg = c.bg_active, bold = true },
    NvimTreeLiveFilterPrefix = { fg = c.warning },
    NvimTreeLiveFilterValue = { fg = c.fg_bright },
    NvimTreeModifiedIcon = { fg = c.warning },
    NvimTreeModifiedFileHL = { fg = c.warning },
    NvimTreeModifiedFolderHL = { fg = c.warning },
    NvimTreeHiddenIcon = { fg = c.fg_muted },
    NvimTreeHiddenFileHL = { fg = c.fg_muted },
    NvimTreeHiddenFolderHL = { fg = c.fg_muted },
    NvimTreeGitDeletedIcon = { link = "LimeiRemoved" },
    NvimTreeGitDirtyIcon = { link = "LimeiChanged" },
    NvimTreeGitIgnoredIcon = { fg = c.fg_muted },
    NvimTreeGitMergeIcon = { fg = c.conflict },
    NvimTreeGitNewIcon = { link = "LimeiAdded" },
    NvimTreeGitRenamedIcon = { fg = c.transform },
    NvimTreeGitStagedIcon = { fg = c.success },
    NvimTreeBookmarkIcon = { fg = c.navigation },
    NvimTreeBookmarkHL = { fg = c.navigation },

    -- oil.nvim
    OilDir = { link = "Directory" },
    OilDirIcon = { link = "Directory" },
    OilLink = { fg = c.information },
    OilLinkTarget = { fg = c.fg_dim },
    OilOrphanLink = { fg = c.error },
    OilOrphanLinkTarget = { fg = c.error },
    OilCopy = { fg = c.literal },
    OilMove = { fg = c.warning },
    OilCreate = { fg = c.literal },
    OilDelete = { fg = c.error },
    OilChange = { fg = c.warning },
    OilRestore = { fg = c.success },
    OilPurge = { fg = c.error },
    OilTrash = { fg = c.error },
    OilTrashSourcePath = { fg = c.fg_muted },
    OilFile = { fg = c.fg },
    OilHidden = { fg = c.fg_muted },
    OilFileHidden = { link = "OilHidden" },
    OilDirHidden = { link = "OilHidden" },
    OilLinkHidden = { link = "OilHidden" },
    OilVtext = { fg = c.fg_muted },
    OilPreviewCursor = { link = "CursorLine" },

    -- oil-git.nvim
    OilGitAdded = { link = "LimeiAdded" },
    OilGitModified = { fg = c.warning },
    OilGitRenamed = { fg = c.transform },
    OilGitUntracked = { fg = c.literal },
    OilGitIgnored = { link = "LimeiPunctuation" },
    -- oil-lsp-diagnostics.nvim uses the central Diagnostic groups directly.

    -- yazi.nvim
    YaziFloat = { link = "NormalFloat" },
    YaziFloatBorder = { link = "FloatBorder" },
  }
end

return M
