local M = {}

function M.get(c)
  return {
    -- telescope.nvim
    TelescopeNormal = { link = "NormalFloat" },
    TelescopePromptNormal = { link = "TelescopeNormal" },
    TelescopeResultsNormal = { link = "TelescopeNormal" },
    TelescopePreviewNormal = { fg = c.fg, bg = c.bg_alt },
    TelescopeBorder = { link = "FloatBorder" },
    TelescopePromptBorder = { link = "TelescopeBorder" },
    TelescopeResultsBorder = { link = "TelescopeBorder" },
    TelescopePreviewBorder = { fg = c.border, bg = c.bg_alt },
    TelescopeTitle = { link = "FloatTitle" },
    TelescopePromptTitle = { link = "TelescopeTitle" },
    TelescopeResultsTitle = { link = "TelescopeTitle" },
    TelescopePreviewTitle = { fg = c.fg_bright, bg = c.bg_alt, bold = true },
    TelescopeSelection = { link = "PmenuSel" },
    TelescopeSelectionCaret = { fg = c.fg_bright, bg = c.bg_selection },
    TelescopeMultiSelection = { fg = c.type },
    TelescopeMultiIcon = { fg = c.fg_dim },
    TelescopeMatching = { fg = c.type, bold = true },
    TelescopePromptPrefix = { fg = c.warning },
    TelescopePromptCounter = { fg = c.fg_muted },
    TelescopePreviewLine = { link = "Visual" },
    TelescopePreviewMatch = { link = "Search" },
    TelescopePreviewDirectory = { link = "Directory" },
    TelescopePreviewLink = { fg = c.information },
    TelescopeResultsClass = { link = "LimeiType" },
    TelescopeResultsConstant = { link = "LimeiConstant" },
    TelescopeResultsField = { link = "LimeiVariable" },
    TelescopeResultsFunction = { link = "LimeiFunction" },
    TelescopeResultsMethod = { link = "LimeiFunction" },
    TelescopeResultsOperator = { link = "LimeiOperator" },
    TelescopeResultsStruct = { link = "LimeiType" },
    TelescopeResultsVariable = { link = "LimeiVariable" },
    TelescopeResultsLineNr = { link = "LineNr" },
    TelescopeResultsIdentifier = { link = "LimeiVariable" },
    TelescopeResultsNumber = { link = "LimeiNumber" },
    TelescopeResultsComment = { link = "Comment" },
    TelescopeResultsSpecialComment = { link = "LimeiDocComment" },
    TelescopeResultsDiffChange = { link = "LimeiChanged" },
    TelescopeResultsDiffAdd = { link = "LimeiAdded" },
    TelescopeResultsDiffDelete = { link = "LimeiRemoved" },
    TelescopeResultsDiffUntracked = { fg = c.fg_muted },

    -- fzf-lua
    FzfLuaNormal = { fg = c.fg, bg = c.bg_popup },
    FzfLuaBorder = { fg = c.border, bg = c.bg_popup },
    FzfLuaTitle = { fg = c.fg_bright, bg = c.bg_popup, bold = true },
    FzfLuaPreviewNormal = { fg = c.fg, bg = c.bg_alt },
    FzfLuaPreviewBorder = { fg = c.border, bg = c.bg_alt },
    FzfLuaPreviewTitle = { fg = c.fg_bright, bg = c.bg_alt, bold = true },
    FzfLuaCursor = { link = "Cursor" },
    FzfLuaCursorLine = { fg = c.fg_bright, bg = c.bg_selection },
    FzfLuaCursorLineNr = { fg = c.warning },
    FzfLuaSearch = { fg = c.type, bold = true },
    FzfLuaScrollBorderEmpty = { fg = c.fg_hidden },
    FzfLuaScrollBorderFull = { fg = c.fg_muted },
    FzfLuaScrollFloatEmpty = { fg = c.fg_hidden },
    FzfLuaScrollFloatFull = { fg = c.fg_muted },
    FzfLuaHelpNormal = { link = "NormalFloat" },
    FzfLuaHelpBorder = { link = "FloatBorder" },
    FzfLuaHeaderBind = { fg = c.fg_dim },
    FzfLuaHeaderText = { fg = c.fg_dim },
    FzfLuaPathColNr = { fg = c.fg_dim },
    FzfLuaPathLineNr = { fg = c.navigation },
    FzfLuaBufName = { fg = c.fg },
    FzfLuaBufId = { fg = c.fg_dim },
    FzfLuaBufNr = { fg = c.fg_dim },
    FzfLuaBufLineNr = { fg = c.navigation },
    FzfLuaBufFlagCur = { fg = c.fg_bright },
    FzfLuaBufFlagAlt = { fg = c.symbol },
    FzfLuaTabTitle = { fg = c.fg_bright },
    FzfLuaTabMarker = { fg = c.fg_bright },
    FzfLuaLivePrompt = { fg = c.warning },
    FzfLuaLiveSym = { fg = c.fg_dim },
    FzfLuaFzfPrompt = { fg = c.warning },
    FzfLuaFzfMatch = { fg = c.type, bold = true },
    FzfLuaFzfPointer = { fg = c.fg_bright },
    FzfLuaFzfMarker = { fg = c.fg_bright },
    FzfLuaFzfScrollbar = { fg = c.fg_muted },
    FzfLuaBackdrop = { fg = c.fg_hidden },

    -- fzf-oil.nvim defines no dedicated highlight groups. It composes the
    -- FzfLua and Oil groups styled by this theme.
  }
end

return M
