local M = {}

function M.get(c)
  return {
    -- diffview.nvim
    DiffviewNormal = { link = "Normal" },
    DiffviewNonText = { link = "NonText" },
    DiffviewCursorLine = { link = "CursorLine" },
    DiffviewWinSeparator = { link = "WinSeparator" },
    DiffviewFilePanelTitle = { fg = c.fg_bright, bold = true },
    DiffviewFilePanelRootPath = { link = "DiffviewFilePanelTitle" },
    DiffviewFilePanelFileName = { fg = c.fg },
    DiffviewFilePanelSelected = { fg = c.fg_bright, bg = c.bg_selection },
    DiffviewFilePanelPath = { fg = c.fg_dim },
    DiffviewFilePanelInsertions = { link = "LimeiAdded" },
    DiffviewFilePanelDeletions = { link = "LimeiRemoved" },
    DiffviewFilePanelConflicts = { fg = c.conflict, bold = true },
    DiffviewFolderName = { link = "Directory" },
    DiffviewFolderSign = { fg = c.fg_hidden },
    DiffviewHash = { fg = c.fg_muted },
    DiffviewReference = { fg = c.information },
    DiffviewReflogSelector = { fg = c.navigation },
    DiffviewStatusAdded = { link = "LimeiAdded" },
    DiffviewStatusUntracked = { fg = c.literal },
    DiffviewStatusModified = { link = "LimeiChanged" },
    DiffviewStatusRenamed = { fg = c.transform },
    DiffviewStatusCopied = { fg = c.transform },
    DiffviewStatusTypeChanged = { link = "LimeiChanged" },
    DiffviewStatusUnmerged = { fg = c.conflict },
    DiffviewStatusUnknown = { fg = c.fg_muted },
    DiffviewStatusDeleted = { link = "LimeiRemoved" },
    DiffviewStatusBroken = { link = "LimeiRemoved" },
    DiffviewStatusIgnored = { fg = c.fg_muted },
    DiffviewDiffAdd = { link = "DiffAdd" },
    DiffviewDiffDelete = { link = "DiffDelete" },
    DiffviewDiffChange = { link = "DiffChange" },
    DiffviewDiffText = { link = "DiffText" },

    -- neogit
    NeogitNormal = { link = "Normal" },
    NeogitNormalFloat = { link = "NormalFloat" },
    NeogitFloatBorder = { link = "FloatBorder" },
    NeogitSignColumn = { link = "SignColumn" },
    NeogitCursorLine = { link = "CursorLine" },
    NeogitCursorLineNr = { link = "CursorLineNr" },
    NeogitWinSeparator = { link = "WinSeparator" },
    NeogitSubtleText = { fg = c.fg_muted },
    NeogitSectionHeader = { fg = c.fg_bright, bold = true },
    NeogitPopupSectionTitle = { link = "NeogitSectionHeader" },
    NeogitPopupBranchName = { fg = c.navigation },
    NeogitPopupSwitchKey = { fg = c.type },
    NeogitPopupOptionKey = { fg = c.type },
    NeogitPopupConfigKey = { fg = c.type },
    NeogitPopupActionKey = { fg = c.type },
    NeogitPopupSwitchEnabled = { fg = c.success },
    NeogitPopupOptionEnabled = { fg = c.success },
    NeogitPopupConfigEnabled = { fg = c.success },
    NeogitPopupSwitchDisabled = { link = "NeogitSubtleText" },
    NeogitPopupOptionDisabled = { link = "NeogitSubtleText" },
    NeogitPopupConfigDisabled = { link = "NeogitSubtleText" },
    NeogitPopupActionDisabled = { link = "NeogitSubtleText" },
    NeogitFilePath = { fg = c.navigation },
    NeogitBranch = { fg = c.navigation, bold = true },
    NeogitBranchHead = { fg = c.navigation, bold = true, underline = true },
    NeogitRemote = { fg = c.information },
    NeogitObjectId = { fg = c.fg_muted },
    NeogitHunkHeader = { fg = c.fg_dim, bg = c.bg_alt, bold = true },
    NeogitHunkHeaderHighlight = { fg = c.fg_bright, bg = c.bg_selection, bold = true },
    NeogitHunkHeaderCursor = { link = "NeogitHunkHeaderHighlight" },
    NeogitDiffHeader = { fg = c.navigation, bg = c.bg_alt, bold = true },
    NeogitDiffHeaderHighlight = { fg = c.fg_bright, bg = c.bg_selection, bold = true },
    NeogitDiffContext = { bg = c.bg },
    NeogitDiffContextHighlight = { bg = c.bg_alt },
    NeogitDiffContextCursor = { bg = c.bg_alt },
    NeogitDiffAdd = { link = "DiffAdd" },
    NeogitDiffAddHighlight = { fg = c.literal, bg = c.bg_selection },
    NeogitDiffAddCursor = { link = "NeogitDiffAddHighlight" },
    NeogitDiffDelete = { link = "DiffDelete" },
    NeogitDiffDeleteHighlight = { fg = c.error, bg = c.bg_selection },
    NeogitDiffDeleteCursor = { link = "NeogitDiffDeleteHighlight" },
    NeogitChangeModified = { link = "LimeiChanged" },
    NeogitChangeAdded = { link = "LimeiAdded" },
    NeogitChangeNewFile = { link = "LimeiAdded" },
    NeogitChangeDeleted = { link = "LimeiRemoved" },
    NeogitChangeRenamed = { fg = c.transform },
    NeogitChangeUpdated = { link = "LimeiChanged" },
    NeogitChangeCopied = { fg = c.transform },
    NeogitChangeUnmerged = { fg = c.conflict, bold = true },
    NeogitSignatureGood = { fg = c.success },
    NeogitSignatureBad = { fg = c.error, bold = true },
    NeogitSignatureMissing = { fg = c.fg_muted },

    -- gitsigns.nvim
    GitSignsAdd = { link = "LimeiAdded" },
    GitSignsAddNr = { link = "LimeiAdded" },
    GitSignsAddLn = { link = "DiffAdd" },
    GitSignsAddCul = { link = "GitSignsAdd" },
    GitSignsChange = { link = "LimeiChanged" },
    GitSignsChangeNr = { link = "LimeiChanged" },
    GitSignsChangeLn = { link = "DiffChange" },
    GitSignsChangeCul = { link = "GitSignsChange" },
    GitSignsDelete = { link = "LimeiRemoved" },
    GitSignsDeleteNr = { link = "LimeiRemoved" },
    GitSignsDeleteLn = { link = "DiffDelete" },
    GitSignsDeleteCul = { link = "GitSignsDelete" },
    GitSignsChangedelete = { fg = c.transform },
    GitSignsChangedeleteNr = { link = "GitSignsChangedelete" },
    GitSignsChangedeleteLn = { link = "DiffChange" },
    GitSignsChangedeleteCul = { link = "GitSignsChangedelete" },
    GitSignsTopdelete = { link = "LimeiRemoved" },
    GitSignsTopdeleteNr = { link = "LimeiRemoved" },
    GitSignsTopdeleteLn = { link = "DiffDelete" },
    GitSignsTopdeleteCul = { link = "LimeiRemoved" },
    GitSignsUntracked = { fg = c.fg_dim },
    GitSignsUntrackedNr = { link = "GitSignsUntracked" },
    GitSignsUntrackedLn = { bg = c.bg_alt },
    GitSignsUntrackedCul = { link = "GitSignsUntracked" },
    GitSignsAddPreview = { link = "DiffAdd" },
    GitSignsDeletePreview = { link = "DiffDelete" },
    GitSignsNoEOLPreview = { fg = c.warning, bg = c.bg_alt },
    GitSignsAddInline = { fg = c.literal, bg = c.bg_selection, bold = true },
    GitSignsChangeInline = { fg = c.warning, bg = c.bg_selection, bold = true },
    GitSignsDeleteInline = { fg = c.error, bg = c.bg_selection, bold = true },
    GitSignsAddLnInline = { link = "GitSignsAddInline" },
    GitSignsChangeLnInline = { link = "GitSignsChangeInline" },
    GitSignsDeleteLnInline = { link = "GitSignsDeleteInline" },
    GitSignsAddVirtLnInline = { link = "GitSignsAddInline" },
    GitSignsChangeVirtLnInline = { link = "GitSignsChangeInline" },
    GitSignsDeleteVirtLnInline = { link = "GitSignsDeleteInline" },
    GitSignsDeleteVirtLn = { link = "DiffDelete" },
    GitSignsDeleteVirtLnInLine = { link = "GitSignsDeleteInline" },
    GitSignsVirtLnum = { fg = c.fg_hidden, bg = c.bg_alt },
    GitSignsCurrentLineBlame = { fg = c.fg_muted },

    -- gitgraph.nvim
    GitGraphBranch1 = { fg = c.literal },
    GitGraphBranch2 = { fg = c.type },
    GitGraphBranch3 = { fg = c.fg_dim },
    GitGraphBranch4 = { fg = c.symbol },
    GitGraphBranch5 = { fg = c.structure },
    GitGraphHash = { fg = c.fg_muted },
    GitGraphTimestamp = { fg = c.fg_dim },
    GitGraphAuthor = { fg = c.fg_dim },
    GitGraphBranchName = { fg = c.literal },
    GitGraphBranchTag = { fg = c.type },
    GitGraphBranchMsg = { fg = c.fg },

    -- undotree
    UndotreeNode = { fg = c.navigation },
    UndotreeCurrent = { fg = c.fg_bright, bold = true },
    UndotreeSeq = { fg = c.fg_dim },
    UndotreeTimeStamp = { fg = c.fg_muted },
  }
end

return M
