local M = {}

function M.get(c)
  local groups = {
    -- render-markdown.nvim
    RenderMarkdownH1 = { fg = c.conflict, bold = true },
    RenderMarkdownH2 = { fg = c.structure, bold = true },
    RenderMarkdownH3 = { fg = c.callable, bold = true },
    RenderMarkdownH4 = { fg = c.type, bold = true },
    RenderMarkdownH5 = { fg = c.information, bold = true },
    RenderMarkdownH6 = { fg = c.symbol, bold = true },
    RenderMarkdownH1Bg = { bg = c.bg_alt },
    RenderMarkdownH2Bg = { link = "RenderMarkdownH1Bg" },
    RenderMarkdownH3Bg = { link = "RenderMarkdownH1Bg" },
    RenderMarkdownH4Bg = { link = "RenderMarkdownH1Bg" },
    RenderMarkdownH5Bg = { link = "RenderMarkdownH1Bg" },
    RenderMarkdownH6Bg = { link = "RenderMarkdownH1Bg" },
    RenderMarkdownCode = { bg = c.bg_alt },
    RenderMarkdownCodeInfo = { fg = c.fg_muted, bg = c.bg_alt },
    RenderMarkdownCodeBorder = { link = "RenderMarkdownCode" },
    RenderMarkdownCodeFallback = { link = "Normal" },
    RenderMarkdownCodeInline = { fg = c.literal, bg = c.bg_alt },
    RenderMarkdownQuote = { fg = c.fg_muted },
    RenderMarkdownQuote1 = { link = "RenderMarkdownQuote" },
    RenderMarkdownQuote2 = { link = "RenderMarkdownQuote" },
    RenderMarkdownQuote3 = { link = "RenderMarkdownQuote" },
    RenderMarkdownQuote4 = { link = "RenderMarkdownQuote" },
    RenderMarkdownQuote5 = { link = "RenderMarkdownQuote" },
    RenderMarkdownQuote6 = { link = "RenderMarkdownQuote" },
    RenderMarkdownInlineHighlight = { link = "RenderMarkdownCodeInline" },
    RenderMarkdownBullet = { link = "LimeiPunctuation" },
    RenderMarkdownDash = { link = "LineNr" },
    RenderMarkdownSign = { link = "SignColumn" },
    RenderMarkdownMath = { link = "@markup.math" },
    RenderMarkdownIndent = { link = "Whitespace" },
    RenderMarkdownHtmlComment = { link = "Comment" },
    RenderMarkdownLink = { fg = c.information },
    RenderMarkdownLinkTitle = { link = "RenderMarkdownLink" },
    RenderMarkdownWikiLink = { link = "RenderMarkdownLink" },
    RenderMarkdownChecked = { fg = c.success },
    RenderMarkdownUnchecked = { fg = c.warning },
    RenderMarkdownTodo = { fg = c.warning },
    RenderMarkdownSuccess = { fg = c.success },
    RenderMarkdownWarn = { fg = c.warning },
    RenderMarkdownError = { fg = c.error },
    RenderMarkdownInfo = { fg = c.information },
    RenderMarkdownHint = { link = "LimeiHint" },
    RenderMarkdownTableHead = { fg = c.fg_bright },
    RenderMarkdownTableRow = { fg = c.fg_dim },

    -- csvview.nvim: neutral tones repeat instead of rainbow columns.
    CsvViewCol0 = { fg = c.fg },
    CsvViewCol1 = { fg = c.fg_dim },
    CsvViewCol2 = { fg = c.fg_muted },
    CsvViewCol3 = { link = "CsvViewCol0" },
    CsvViewCol4 = { link = "CsvViewCol1" },
    CsvViewCol5 = { link = "CsvViewCol2" },
    CsvViewCol6 = { link = "CsvViewCol0" },
    CsvViewCol7 = { link = "CsvViewCol1" },
    CsvViewCol8 = { link = "CsvViewCol2" },
    CsvViewDelimiter = { fg = c.fg_hidden },
    CsvViewComment = { link = "Comment" },
    CsvViewHeaderLine = { fg = c.fg_bright, bg = c.bg_alt, bold = true },
    CsvViewStickyHeaderSeparator = { link = "WinSeparator" },
  }

  return groups
end

return M
