local M = {}

local palette = require("limei.palette")
local colors = palette.get()
local ansi = palette.terminal(colors)

local function hex(color)
  return color:sub(2)
end

local function lines(values)
  return table.concat(values, "\n") .. "\n"
end

local function quoted(values)
  local result = {}
  for _, value in ipairs(values) do
    table.insert(result, ('"%s"'):format(value))
  end
  return table.concat(result, ", ")
end

local function render_kitty()
  local output = {
    "# Generated by scripts/extras.lua",
    "foreground " .. colors.fg,
    "background " .. colors.bg,
    "selection_foreground " .. colors.fg_bright,
    "selection_background " .. colors.bg_selection,
    "cursor " .. colors.fg_bright,
    "cursor_text_color " .. colors.bg,
  }
  for index, color in ipairs(ansi) do
    table.insert(output, ("color%d %s"):format(index - 1, color))
  end
  return lines(output)
end

local function render_ghostty()
  local output = {
    "# Generated by scripts/extras.lua",
    "background = " .. colors.bg,
    "foreground = " .. colors.fg,
    "cursor-color = " .. colors.fg_bright,
    "cursor-text = " .. colors.bg,
    "selection-background = " .. colors.bg_selection,
    "selection-foreground = " .. colors.fg_bright,
  }
  for index, color in ipairs(ansi) do
    table.insert(output, ("palette = %d=%s"):format(index - 1, color))
  end
  return lines(output)
end

local function render_foot()
  return lines({
    "# Generated by scripts/extras.lua",
    "[colors]",
    "background=" .. hex(colors.bg),
    "foreground=" .. hex(colors.fg),
    "selection-foreground=" .. hex(colors.fg_bright),
    "selection-background=" .. hex(colors.bg_selection),
    "regular0=" .. hex(ansi[1]),
    "regular1=" .. hex(ansi[2]),
    "regular2=" .. hex(ansi[3]),
    "regular3=" .. hex(ansi[4]),
    "regular4=" .. hex(ansi[5]),
    "regular5=" .. hex(ansi[6]),
    "regular6=" .. hex(ansi[7]),
    "regular7=" .. hex(ansi[8]),
    "bright0=" .. hex(ansi[9]),
    "bright1=" .. hex(ansi[10]),
    "bright2=" .. hex(ansi[11]),
    "bright3=" .. hex(ansi[12]),
    "bright4=" .. hex(ansi[13]),
    "bright5=" .. hex(ansi[14]),
    "bright6=" .. hex(ansi[15]),
    "bright7=" .. hex(ansi[16]),
  })
end

local function render_alacritty()
  return lines({
    "# Generated by scripts/extras.lua",
    "[colors.primary]",
    ('background = "%s"'):format(colors.bg),
    ('foreground = "%s"'):format(colors.fg),
    "",
    "[colors.cursor]",
    ('cursor = "%s"'):format(colors.fg_bright),
    ('text = "%s"'):format(colors.bg),
    "",
    "[colors.selection]",
    ('background = "%s"'):format(colors.bg_selection),
    ('text = "%s"'):format(colors.fg_bright),
    "",
    "[colors.normal]",
    ('black = "%s"'):format(ansi[1]),
    ('red = "%s"'):format(ansi[2]),
    ('green = "%s"'):format(ansi[3]),
    ('yellow = "%s"'):format(ansi[4]),
    ('blue = "%s"'):format(ansi[5]),
    ('magenta = "%s"'):format(ansi[6]),
    ('cyan = "%s"'):format(ansi[7]),
    ('white = "%s"'):format(ansi[8]),
    "",
    "[colors.bright]",
    ('black = "%s"'):format(ansi[9]),
    ('red = "%s"'):format(ansi[10]),
    ('green = "%s"'):format(ansi[11]),
    ('yellow = "%s"'):format(ansi[12]),
    ('blue = "%s"'):format(ansi[13]),
    ('magenta = "%s"'):format(ansi[14]),
    ('cyan = "%s"'):format(ansi[15]),
    ('white = "%s"'):format(ansi[16]),
  })
end

local function render_wezterm()
  return lines({
    "-- Generated by scripts/extras.lua",
    "return {",
    ('  foreground = "%s",'):format(colors.fg),
    ('  background = "%s",'):format(colors.bg),
    ('  cursor_bg = "%s",'):format(colors.fg_bright),
    ('  cursor_fg = "%s",'):format(colors.bg),
    ('  selection_bg = "%s",'):format(colors.bg_selection),
    ('  selection_fg = "%s",'):format(colors.fg_bright),
    ("  ansi = { %s },"):format(quoted(vim.list_slice(ansi, 1, 8))),
    ("  brights = { %s },"):format(quoted(vim.list_slice(ansi, 9, 16))),
    "}",
  })
end

local function render_windows_terminal()
  local names = {
    "black",
    "red",
    "green",
    "yellow",
    "blue",
    "purple",
    "cyan",
    "white",
    "brightBlack",
    "brightRed",
    "brightGreen",
    "brightYellow",
    "brightBlue",
    "brightPurple",
    "brightCyan",
    "brightWhite",
  }
  local output = {
    "{",
    '  "name": "Limei",',
    ('  "background": "%s",'):format(colors.bg),
    ('  "foreground": "%s",'):format(colors.fg),
    ('  "cursorColor": "%s",'):format(colors.fg_bright),
    ('  "selectionBackground": "%s",'):format(colors.bg_selection),
  }
  for index, name in ipairs(names) do
    local suffix = index == #names and "" or ","
    table.insert(output, ('  "%s": "%s"%s'):format(name, ansi[index], suffix))
  end
  table.insert(output, "}")
  return lines(output)
end

local generated = {
  ["extras/alacritty/limei.toml"] = render_alacritty(),
  ["extras/foot/limei.ini"] = render_foot(),
  ["extras/ghostty/limei"] = render_ghostty(),
  ["extras/kitty/limei.conf"] = render_kitty(),
  ["extras/wezterm/limei.lua"] = render_wezterm(),
  ["extras/windows-terminal/limei.json"] = render_windows_terminal(),
}

function M.write()
  for path, content in pairs(generated) do
    vim.fn.mkdir(vim.fs.dirname(path), "p")
    vim.fn.writefile(vim.split(content:sub(1, -2), "\n", { plain = true }), path)
  end
end

function M.check()
  local failures = {}
  for path, expected in pairs(generated) do
    local actual = table.concat(vim.fn.readfile(path), "\n") .. "\n"
    if actual ~= expected then
      table.insert(failures, path)
    end
  end
  if #failures > 0 then
    vim.api.nvim_err_writeln("generated extras are stale: " .. table.concat(failures, ", "))
    vim.cmd.cquit()
    return
  end
  print("limei.nvim generated extras are current")
end

return M
